### ISSUE TITLE
How to add passive listener into zoom event?

### ISSUE THREAD

**Issue by MUTHUKUMAR73737** [d3/d3-selection#280] opened 2021-03-25 07:49 UTC
![image](https://user-images.githubusercontent.com/37654694/112436571-dafd9100-8d6b-11eb-8b65-3311e9a3a732.png)

I am getting above error when I drag inside the chart.

`    d3.select("svg")
      .call(
        d3.zoom()
          .scaleExtent([1, 10])
          .translateExtent([[0, 0], [400, 215]])
          .extent([[0, 0], [400, 215]])
          .on("zoom", function (event) {
          // stuff here
          })`
          
Relevant Analysis:
[https://developers.google.com/web/updates/2016/06/passive-event-listeners](url)
[https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener](url)
[https://github.com/d3/d3-selection/blob/v2.0.0/README.md#selection_on](url)

From the above analysis, what I observed is we should turn off the passive event listener.

I would like to pass additional options like passive event listener in the d3js event handling.

I am using d3js version 6.3.1

Please help me to resolve this issue.

**Comment by Fil** [comment] 2021-03-25 08:07
duplicate of https://github.com/d3/d3-zoom/issues/231

**Closed by Fil** 2021-03-25 08:07 UTC
