### ISSUE TITLE
Missing null check

### ISSUE THREAD

**Issue by isakbm** [d3/d3-selection#316] opened 2024-02-27 16:13 UTC
https://github.com/d3/d3-selection/issues/315

Would be great to get someone's second opinion on this, I don't fully understand [mbostock](https://github.com/mbostock) 's view.

**Comment by mbostock** [comment] 2024-02-27 16:21
Duplicate of #315. Please comment there if you want to continue discussing.

**Closed as not planned by mbostock** 2024-02-27 16:21 UTC
