### ISSUE TITLE
Has exit() to be invoked when key changes?

### ISSUE THREAD

**Issue by ZitRos** [d3/d3-selection#105] opened 2016-12-03 23:23 UTC
Hello. Today I reached D3 behavior that seems unexpected to me.

Look at this example ([JSFiddle](https://jsfiddle.net/smz86aub/1/)):

```js
let data = [
  { id: 1, label: "Hello" },
  { id: 2, label: "World" }
];
  
function update () {
  let div = d3.select("body").selectAll("div").data(data, d => d.id);
  div.exit().remove();
  div.enter().append("div").text(d => d.label);
}

d3.select("#pressobj").on("click", () => {
  data[0] = { id: 3, label: "New" };
  update();
});

d3.select("#pressid").on("click", () => {
  data[0].id = 3;
  data[0].label = "New";
  update();
});

update();
```

It is expected `exit()` to be invoked when the id function `d => d.id` returns new value on the same element, is it? If it is, why re-assigning the `id` property doesn't update the view, but re-assigning object reference does? Is there a way to make `id` property assignment work as expected? (I have a complex tree structure and it is quite expensive to reassign the whole object instead of just it's id)

Thank you!

**Comment by mbostock** [comment] 2016-12-04 00:36
This is the expected behavior.

Previously-used keys are not stored anywhere internal to D3. If you overwrite your *datum*.id property, you are effectively changing the value of the old key in-place, and thus your exit selection is always empty. As noted in the API Reference, your key function is invoked for each element in the selection, being passed the element’s current datum (and index) bound to that element; it is also invoked for each datum in the new data, being passed the new datum (and index). Since those objects are the same in your case, the old and new keys will always be equal (because you are updating both the old key and the new key by assigning to *datum*.id), and thus the enter and exit selections will always be empty on pressid click.

If you want to mutate the data in-place, you must store the previous key value somewhere. One way to do that would be to store it in the DOM as an attribute:

```js
var div = d3.select("body").selectAll("div")
  .data(data, function(d) { return this.getAttribute("key") || d.id; });

div.exit().remove();

div.enter().append("div")
    .attr("key", function(d) { return d.id; })
    .text(function(d) { return d.label; });
```

With this approach, you can’t use fat-arrow functions because you need *this* to retrieve the attribute from the selected element. When the key function is evaluated for a selected element, *this* refers to the selected element; when the key function is evaluated for a new datum, *this* refers to the parent element (here the body).

If you prefer, you could use a hidden \_key property on DOM nodes:

```js
var div = d3.select("body").selectAll("div")
  .data(data, function(d) { return this._key || d.id; });

div.exit().remove();

div.enter().append("div")
    .each(function(d) { this._key = d.id; })
    .text(function(d) { return d.label; });
```

**Closed by mbostock** 2016-12-04 00:36 UTC

**Comment by ZitRos** [comment] 2016-12-04 01:05
Thank you very much for such detailed explanation, Mike! Now the idea is clear for me and the approach described works perfectly. Thank you!
