### ISSUE TITLE
Add `sideEffects` in package.json?

### ISSUE THREAD

**Issue by mindrones** [d3/d3-selection#223] opened 2019-08-04 16:42 UTC
It would be nice to know if a d3 module has side effects without having to read the code, by inspecting the [`sideEffects`](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) property in `package.json`.

This would permit to enhance tree shaking by reading that value programmatically and set rollup's `treeshake.moduleSideEffects` accordingly.

If this makes sense and is doable, this would apply to all of d3 modules (*EDIT:* especially if you'll [do a major version bump across all the modules](https://github.com/d3/d3/issues/3333#issuecomment-516613136)!)

Thanks!

**Comment by mbostock** [comment] 2019-08-05 04:31
Duplicate of https://github.com/d3/d3/issues/3131. This is planned, but please see caveats in that discussion and comments would be welcome.

**Closed by mbostock** 2019-08-05 04:31 UTC
