### ISSUE TITLE
Did version 1.3 break d3-zoom? Another case here...

### ISSUE THREAD

**Issue by peter-poki** [d3/d3-selection#163] opened 2018-01-30 16:05 UTC
I have also problem with version 1.3, it really seems to break d3-zoom.

Here is a example of one error
https://stackblitz.com/edit/react-vm4eb6?file=index.js
(its a modified example of https://bl.ocks.org/mbostock/4e3925cdc804db257a86fdef3a032a45 )

Also I suspect the new release, because everything worked before weekend, but after we run new automated builds, application is broken. And I could not simulated it locally, because I had node modules already downloaded. But when I did yarn install I got the same problem. that is becasue d3-zoom has in his dependencie "d3-selection": "1", which overtakes my 1.2 version with new version 1.3

I have locally in bigger setup also problem like this
![image](https://user-images.githubusercontent.com/22402252/35576347-0a2c5a0a-05df-11e8-9988-19d4ae1f59c0.png)

Do you have any ideas?

**Comment by mbostock** [comment] 2018-01-30 16:32
Duplicate of d3/d3#3256. Possible fixes: 1. Upgrade to 5.0. 2. Use the D3 modules directly rather than the `d3` default bundle. 3. Use your package manager, e.g., yarn’s resolutions feature, to pin the versions of the D3 modules so they are consistent with the `d3` package you are using.

**Closed by mbostock** 2018-01-30 16:32 UTC
